title: Univeth
description: Portfolio
theme: just-the-docs
#
# Color scheme supports "light" (default) and "dark"
color_scheme: dark

favicon_ico: "3665994.png"
logo: "3665994.png"

permalink: /:title/



url: https://just-the-docs.github.io

